{
 "title": "V2Ray Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "query_result(count_over_time(v2ray_up[$__range]))"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "query_result(count_over_time(v2ray_up{job=\"$job\"}[$__range]))"
   }
  ]
 },
 "panels": [
  {
   "title": "Outbounds Online",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (max by (outbound)( v2ray_observatory_alive{job=~\"$job\",instance=~\"$instance\"} == 1))"
    }
   ]
  },
  {
   "title": "Real-Time Overview",
   "type": "table",
   "gridPos": { "h": 4, "w": 9, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "v2ray_uptime_seconds{job=~\"$job\",instance=~\"$instance\"}"
    },
    {
     "expr": "sum by (instance) (increase(v2ray_traffic_downlink_bytes_total{job=~\"$job\",instance=~\"$instance\",dimension=\"outbound\",src=\"all\"}[$__range]))"
    },
    {
     "expr": "sum by (instance) (increase(v2ray_traffic_uplink_bytes_total{job=~\"$job\",instance=~\"$instance\",dimension=\"outbound\",src=\"all\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Total Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(v2ray_traffic_downlink_bytes_total{job=~\"$job\",instance=~\"$instance\",dimension=\"outbound\",src=\"all\"}[$__rate_interval]))",
     "legendFormat": "Downlink"
    },
    {
     "expr": "sum(irate(v2ray_traffic_uplink_bytes_total{job=~\"$job\",instance=~\"$instance\",dimension=\"outbound\",src=\"all\"}[$__rate_interval]))",
     "legendFormat": "Uplink"
    }
   ]
  },
  {
   "title": "Outbounds Offline",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (max by (outbound)( v2ray_observatory_alive{job=~\"$job\",instance=~\"$instance\"} == 0))"
    }
   ]
  },
  {
   "title": "Outbounds Online Stats",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 9, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count (max by (outbound)( v2ray_observatory_alive{job=~\"$job\",instance=~\"$instance\"} == 1))",
     "legendFormat": "Alive"
    },
    {
     "expr": "count (max by (outbound)( v2ray_observatory_alive{job=~\"$job\",instance=~\"$instance\"} == 0))",
     "legendFormat": "Dead"
    }
   ]
  },
  { "title": "$instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "instance" },
  {
   "title": "Real-Time User Overview",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(v2ray_traffic_downlink_bytes_total{job=~\"$job\",instance=~\"$instance\", src!=\"all\"}[$__range])"
    },
    {
     "expr": "increase(v2ray_traffic_uplink_bytes_total{job=~\"$job\",instance=~\"$instance\", src!=\"all\"}[$__range])"
    }
   ]
  },
  {
   "title": "Real-Time Total Overview",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(v2ray_traffic_downlink_bytes_total{job=~\"$job\",instance=~\"$instance\", src=\"all\"}[$__range])"
    },
    {
     "expr": "increase(v2ray_traffic_uplink_bytes_total{job=~\"$job\",instance=~\"$instance\", src=\"all\"}[$__range])"
    }
   ]
  },
  {
   "title": "Real-Time User Totalview",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (dimension,src) (increase(v2ray_traffic_downlink_bytes_total{job=~\"$job\",instance=~\"$instance\", src!=\"all\"}[$__range]))"
    },
    {
     "expr": "sum by (dimension,src) (increase(v2ray_traffic_uplink_bytes_total{job=~\"$job\",instance=~\"$instance\", src!=\"all\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Connect attempts of Users",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(v2ray_connection_attempt_total{job=~\"$job\",instance=~\"$instance\",dimension=\"outbound\",src!=\"all\"}[$__rate_interval])) by (src,target)",
     "legendFormat": "{{src}} -> {{target}}"
    }
   ]
  },
  {
   "title": "HTTPS Realtime Latency of Outbounds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (outbound) (v2ray_observatory_delay_seconds{job=~\"$job\",instance=~\"$instance\"} < 10) ",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "HTTPS Success Rate of Outbounds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1-(\n    v2ray_observatory_health_ping_count{job=~\"$job\",instance=~\"$instance\",result=\"fail\"}\n    / ignoring(result) \n    v2ray_observatory_health_ping_count{job=~\"$job\",instance=~\"$instance\",result=\"total\"}\n)",
     "legendFormat": "{{outbound}}"
    }
   ]
  },
  {
   "title": "HTTPS Average Latency of Outbounds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (outbound) (v2ray_observatory_health_ping_seconds{job=~\"$job\",instance=~\"$instance\",stat=\"avg\"} > 0)",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "HTTPS Standard Deviation Latency of Outbounds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (outbound) (v2ray_observatory_health_ping_deviation_seconds{job=~\"$job\",instance=~\"$instance\"} > 0)",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Download Speed of Outbounds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(v2ray_traffic_downlink_bytes_total{job=~\"$job\",instance=~\"$instance\",dimension=\"outbound\",src=\"all\"}[$__rate_interval])) by (target)",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Upload Speed of Outbounds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(v2ray_traffic_uplink_bytes_total{job=~\"$job\",instance=~\"$instance\",dimension=\"outbound\",src=\"all\"}[$__rate_interval])) by (target)",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Download Speed of Users per Outbound",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(v2ray_traffic_downlink_bytes_total{job=~\"$job\",instance=~\"$instance\",dimension=\"outbound\",src!=\"all\"}[$__rate_interval])) by (src, target)",
     "legendFormat": "{{src}} <- {{target}}"
    }
   ]
  },
  {
   "title": "Upload Speed of Users per Outbound",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(v2ray_traffic_uplink_bytes_total{job=~\"$job\",instance=~\"$instance\",dimension=\"outbound\",src!=\"all\"}[$__rate_interval])) by (src,target)",
     "legendFormat": "{{src}} -> {{target}}"
    }
   ]
  },
  {
   "title": "Download Speed of Users",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(v2ray_traffic_downlink_bytes_total{job=~\"$job\",instance=~\"$instance\",dimension=\"outbound\",src!=\"all\"}[$__rate_interval])) by (src)",
     "legendFormat": "{{src}}"
    }
   ]
  },
  {
   "title": "Upload Speed of Users",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(v2ray_traffic_uplink_bytes_total{job=~\"$job\",instance=~\"$instance\",dimension=\"outbound\",src!=\"all\"}[$__rate_interval])) by (src)",
     "legendFormat": "{{src}}"
    }
   ]
  }
 ]
}